language: node_js

node_js:
  - "node"
  - "lts/*"

install:
  - yarn

cache:
  directories:
    - "node_modules"
    - ~/.npm

notifications:
  email: false
  
jobs:
  include:
    - stage: test
      script:
        - yarn test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      script:
        - npm run release
      after_sucess: skip

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/